drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence GlobalSequencer;
drop table AnswrAllCMD cascade constraints;
drop table Srvr cascade constraints;
drop table Fldr cascade constraints;
drop table AddRcvrCMD cascade constraints;
drop table CrtFldrCMD cascade constraints;
drop table AnswrCMD cascade constraints;
drop table CmmndCrdntr cascade constraints;
drop table Ml cascade constraints;
drop table SndCMD cascade constraints;
drop table AccntMngr cascade constraints;
drop table CrtAccntCMD cascade constraints;
drop table CrtDrftCMD cascade constraints;
drop table CmmnDt cascade constraints;
drop table CmmndExctr cascade constraints;
drop table abstrctAcc cascade constraints;
drop table AccntFldrs cascade constraints;
drop table FldrMls cascade constraints;
drop table CmmndCrdntrExctr cascade constraints;
drop table MlRcvrs cascade constraints;
drop table AccntMngrAccnts cascade constraints;
drop table CmmndExctrCommands cascade constraints;
