drop package CmmndCrdntrFacade;
drop package SrvrFacade;
drop package CmmnDtFacade;
drop package CmmndExctrFacade;
drop package ManyServices;
drop package ClassFacade;
drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence GlobalSequencer;
drop table CmmndCrdntr cascade constraints;
drop table Srvr cascade constraints;
drop table CmmnDt cascade constraints;
drop table CmmndExctr cascade constraints;
drop table CmmndCrdntrExctr cascade constraints;
drop table CmmndExctrCommands cascade constraints;
