drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence GlobalSequencer;
drop table Srvr cascade constraints;
drop table ClpBrdStt cascade constraints;
drop table Cntn cascade constraints;
drop table AddCntnCMD cascade constraints;
drop table DltCMD cascade constraints;
drop table CmmndCrdntr cascade constraints;
drop table FlSstm cascade constraints;
drop table ClpBrd cascade constraints;
drop table CmmnDt cascade constraints;
drop table CmmndExctr cascade constraints;
drop table ChngCntntsCMD cascade constraints;
drop table CmmndCrdntrExctr cascade constraints;
drop table CmmndExctrCommands cascade constraints;
drop table DrctrCntnts cascade constraints;
