drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence GlobalSequencer;
drop table Accnt cascade constraints;
drop table Srvr cascade constraints;
drop table Mngr cascade constraints;
drop table CmmndCrdntr cascade constraints;
drop table Entr cascade constraints;
drop table BkCMD cascade constraints;
drop table Trnsfr cascade constraints;
drop table CrtTrnsfrCMD cascade constraints;
drop table CrtAccntCMD cascade constraints;
drop table CmmnDt cascade constraints;
drop table CmmndExctr cascade constraints;
drop table AccntEntrs cascade constraints;
drop table MngrCrrntAccnts cascade constraints;
drop table MngrOpnTrnsfrs cascade constraints;
drop table CmmndCrdntrExctr cascade constraints;
drop table CmmndExctrCommands cascade constraints;
