drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SAccntWrpprAccnt;
drop table AccntWrpprAccnt cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SEntr;
drop table Entr cascade constraints;
drop sequence SAccntHndl;
drop table AccntHndl cascade constraints;
drop sequence SCrtTrnsfrCMD;
drop table CrtTrnsfrCMD cascade constraints;
drop sequence SCrtAccntCMD;
drop table CrtAccntCMD cascade constraints;
drop sequence SAccntMngrCrrntAccnts;
drop table AccntMngrCrrntAccnts cascade constraints;
drop sequence STrnsfrMngr;
drop table TrnsfrMngr cascade constraints;
drop sequence SWrpprRccl;
drop table WrpprRccl cascade constraints;
drop sequence SSrvrAccnts;
drop table SrvrAccnts cascade constraints;
drop sequence SAbstrTrnsfr;
drop table AbstrTrnsfr cascade constraints;
drop sequence STrnsfrStt;
drop table TrnsfrStt cascade constraints;
drop sequence SSubj;
drop table Subj cascade constraints;
drop sequence SBkCMD;
drop table BkCMD cascade constraints;
drop sequence SAccntMngr;
drop table AccntMngr cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SAccntEntrs;
drop table AccntEntrs cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SAccntMngrCrrntAccntsObs;
drop table AccntMngrCrrntAccntsObs cascade constraints;
drop sequence STrnsfrMngrTrnsfrs;
drop table TrnsfrMngrTrnsfrs cascade constraints;
drop sequence SWrpprRcclRccld;
drop table WrpprRcclRccld cascade constraints;
drop sequence SSubjObs;
drop table SubjObs cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
