drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SCrtPrgrmCMD;
drop table CrtPrgrmCMD cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SPrgrmSGrp;
drop table PrgrmSGrp cascade constraints;
drop sequence SStrtStdGrpCMD;
drop table StrtStdGrpCMD cascade constraints;
drop sequence SMdlMngr;
drop table MdlMngr cascade constraints;
drop sequence SUnt;
drop table Unt cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SStdGrp;
drop table StdGrp cascade constraints;
drop sequence SGrdSstm;
drop table GrdSstm cascade constraints;
drop sequence SAdd_S2GCMD;
drop table Add_S2GCMD cascade constraints;
drop sequence SAddMdlTGrpCMD;
drop table AddMdlTGrpCMD cascade constraints;
drop sequence SAddMdlTPrgCMD;
drop table AddMdlTPrgCMD cascade constraints;
drop sequence SPrgrmMngr;
drop table PrgrmMngr cascade constraints;
drop sequence SPrgrm;
drop table Prgrm cascade constraints;
drop sequence SUntSGrp;
drop table UntSGrp cascade constraints;
drop sequence SCrtStdntCMD;
drop table CrtStdntCMD cascade constraints;
drop sequence SStdntMngr;
drop table StdntMngr cascade constraints;
drop sequence SStdnt;
drop table Stdnt cascade constraints;
drop sequence SCrtMdlCMD;
drop table CrtMdlCMD cascade constraints;
drop sequence SStdGrpMngr;
drop table StdGrpMngr cascade constraints;
drop sequence SGrIn2or3;
drop table GrIn2or3 cascade constraints;
drop sequence SUntStdnt;
drop table UntStdnt cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SAddUntCMD;
drop table AddUntCMD cascade constraints;
drop sequence SMdlAbstrct;
drop table MdlAbstrct cascade constraints;
drop sequence Sm_abstr_gr;
drop table m_abstr_gr cascade constraints;
drop sequence SChngCPOnMdlCMD;
drop table ChngCPOnMdlCMD cascade constraints;
drop sequence SSCPonMWUCMD;
drop table SCPonMWUCMD cascade constraints;
drop sequence SPrgrmStdnt;
drop table PrgrmStdnt cascade constraints;
drop sequence SChngGrdSstmCMD;
drop table ChngGrdSstmCMD cascade constraints;
drop sequence SChngCPOnUntCMD;
drop table ChngCPOnUntCMD cascade constraints;
drop sequence SGrdsInTnth;
drop table GrdsInTnth cascade constraints;
drop sequence Sm_abstr_st;
drop table m_abstr_st cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SPrgrmSGrpMdls;
drop table PrgrmSGrpMdls cascade constraints;
drop sequence SMdlGrpSGrpMdls;
drop table MdlGrpSGrpMdls cascade constraints;
drop sequence SMdlMngrMdls;
drop table MdlMngrMdls cascade constraints;
drop sequence SMdlGrpMdls;
drop table MdlGrpMdls cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SStdGrpStdnts;
drop table StdGrpStdnts cascade constraints;
drop sequence SPrgrmMngrPrgrms;
drop table PrgrmMngrPrgrms cascade constraints;
drop sequence SPrgrmMdls;
drop table PrgrmMdls cascade constraints;
drop sequence SStdntMngrStdnts;
drop table StdntMngrStdnts cascade constraints;
drop sequence SStdGrpMngrGrps;
drop table StdGrpMngrGrps cascade constraints;
drop sequence Sm_unit_grUnts;
drop table m_unit_grUnts cascade constraints;
drop sequence SMdlWthUntsUnts;
drop table MdlWthUntsUnts cascade constraints;
drop sequence SPrgrmStdntMdls;
drop table PrgrmStdntMdls cascade constraints;
drop sequence Sm_unit_studUnts;
drop table m_unit_studUnts cascade constraints;
drop sequence SMdlGrpStdntMdls;
drop table MdlGrpStdntMdls cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
